apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-secret
data:
  DB_Password: test1234
--- 
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql